version: '3.4'

services:
  yahoofinancedb:
    container_name: yahoofinancedb
    restart: always
    ports:
      - "6379:6379"

  yahoofinance.api:
    container_name: yahoofinance.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:MyRedisConStr=yahoofinancedb:6379"
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    depends_on:
      - yahoofinancedb
    ports:
      - "8080"
      - "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro